version: '2.0'
services:
  db:
    image: mariadb:10.5
    container_name: seafile-mysql
    restart: unless-stopped
    env_file: .env
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - seafile-net

  memcached:
    image: memcached:alpine
    container_name: seafile-memcached
    restart: unless-stopped
    networks:
      - seafile-net

  seafile:
    image: seafileltd/seafile-pro-mc:12.0-latest
    container_name: seafile
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - seafile-data:/shared
    env_file: .env
    depends_on:
      - db
      - memcached
    networks:
      - seafile-net

volumes:
  db-data:
  seafile-data:

networks:
  seafile-net:
